server:
  port: 48080


#指定注册中心地址
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}}/temppark_service/


#服务的名称
spring:
  application:
    name: temppark-service
